services:
  opensearch_indexer_tests:
    build:
      context: ./data_management/opensearch_indexer
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./test_results:/test_results
    working_dir: /app
    entrypoint: ""
    command:
    - sh
    - -c
    - |
        set -e

        apt-get update

        echo 'Installing Python test dependencies...'
        pip install -r data_management/opensearch_indexer/requirements-dev.txt

        pytest \
          --cov=data_management/opensearch_indexer/opensearch_indexer \
          --cov-report=xml:/test_results/coverage.xml \
          --cov-report=term-missing \
          -vvs data_management/opensearch_indexer/tests

  postgres:
    image: postgres@sha256:1ffc019dae94eca6b09a49ca67d37398951346de3c3d0cfe23d8d4ca33da83fb # postgres:18.0 with digest for immutability
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testPass123 # pragma: allowlist secret
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
