[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.bandit]
exclude_dirs = ['*_test.py', '*/test_*.py', 'venv', 'node_modules']
skips = ["B105"]

[tool.poetry.dependencies]
python = "^3.11"
cssmin = "0.2.0"
email-validator = "2.1.0.post1"
flask-compress = "1.14"
flask-limiter = "3.5.1"
flask-talisman = "1.1.0"
flask = "3.0.2"
govuk-frontend-jinja = "3.0.0"
govuk-frontend-wtf = "3.0.0"
gunicorn = "21.2.0"
jsmin = "3.0.1"
python-dotenv = "1.0.1"
redis = "5.0.1"
python-keycloak = "3.9.0"
boto3 = "1.28.85"
botocore = "1.31.85"
flask-sqlalchemy = "^3.1.1"
psycopg2-binary = "^2.9.9"
setuptools = "^69.1.0"
zappa = "^0.58.0"

[tool.poetry.group.dev.dependencies]
testing-postgresql = "^1.3.0"
bandit = "1.7.7"
black = "24.2.0"
flake8-bugbear = "24.2.6"
bs4 = "^0.0.2"
isort = "5.13.2"
moto = "^5.0.1"
pep8-naming = "0.13.3"
pip-tools = "7.4.0"
pur = "7.3.1"
pyopenssl = "^24"
pytest-cov = "^4.1.0"
pytest-flask = "^1.2.0"
pytest-playwright = "0.4.4"
pre-commit = "^3.6.1"
safety = "3.0.1"
factory-boy = "^3.3.0"
pyjwt = "^2.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80

[tool.isort]
line_length = 80
