[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.bandit]
exclude_dirs = ['*_test.py', '*/test_*.py', 'venv', 'node_modules']
skips = ["B105"]

[tool.poetry.dependencies]
python = "^3.11"
cssmin = "0.2.0"
flask-compress = "1.15"
flask-talisman = "1.1.0"
flask = "3.0.3"
govuk-frontend-jinja = "3.1.0"
govuk-frontend-wtf = "3.1.0"
gunicorn = "22.0.0"
jsmin = "3.0.1"
python-dotenv = "1.0.1"
redis = "5.0.7"
python-keycloak = "4.2.0"
boto3 = "^1"
flask-sqlalchemy = "^3.1.1"
psycopg2-binary = "^2.9.9"
setuptools = "^70.1.1"
flask-s3 = "^0.3.3"

[tool.poetry.group.dev.dependencies]
testing-postgresql = "^1.3.0"
bandit = "1.7.9"
black = "24.4.2"
flake8-bugbear = "24.4.26"
bs4 = "^0.0.2"
isort = "5.13.2"
moto = "^5.0.10"
pep8-naming = "0.14.1"
pip-tools = "7.4.1"
pyopenssl = "^24"
pytest-cov = "^5.0.0"
pytest-flask = "^1.2.0"
pytest-playwright = "0.5.1"
pre-commit = "^3.7.1"
safety = "3.2.3"
factory-boy = "^3.3.0"
pyjwt = "^2.8.0"
pytest-repeat = "^0.9.3"
pytest-playwright-visual = "^2.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80

[tool.isort]
line_length = 80
