# GitHub CI specific Docker Compose overrides - Fixed IP approach
services:
  # Single OpenSearch node with fixed IP
  opensearch-node1:
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=false
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - plugins.security.disabled=true
      - network.host=0.0.0.0
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    networks:
      ci_network:
        ipv4_address: 192.168.100.10
    # Remove custom container name to use default naming

  # Disable node2 for CI
  opensearch-node2:
    deploy:
      replicas: 0

  webapp:
    # Remove custom container name to use default naming
    networks:
      ci_network:
        ipv4_address: 192.168.100.20
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - CONFIG_SOURCE=ENVIRONMENT_VARIABLES
      - DB_HOST=192.168.100.30
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_SSL_ROOT_CERTIFICATE=/app/local_services/webapp_postgres_certs/root-ca.pem
      - SQLALCHEMY_SSL_MODE=disable
      - KEYCLOAK_BASE_URI=http://192.168.100.40:8080
      - KEYCLOAK_CLIENT_ID=ayr-beta
      - KEYCLOAK_REALM_NAME=tdr
      - KEYCLOAK_CLIENT_SECRET=test-client-secret
      - AWS_ENDPOINT_URL=https://192.168.100.50:9000
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_REGION=eu-west-2
      - AWS_CA_BUNDLE=/app/local_services/minio_certs/root-ca.crt
      - SECRET_KEY=test-secret-key
      - DEFAULT_PAGE_SIZE=10
      - DEFAULT_DATE_FORMAT=DD/MM/YYYY
      - RECORD_BUCKET_NAME=test-record-download
      - FLASKS3_ACTIVE=False
      - FLASKS3_CDN_DOMAIN=localhost
      - FLASKS3_BUCKET_NAME=test-record-download
      - PERF_TEST=False
      # Use fixed IP for OpenSearch
      - OPEN_SEARCH_HOST=http://192.168.100.10:9200
      - OPEN_SEARCH_USERNAME=admin
      - OPEN_SEARCH_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - OPEN_SEARCH_TIMEOUT=30
    depends_on:
      - webapp_postgres
      - keycloak
      - minio
      - opensearch-node1

  keycloak:
    # Remove custom container name to use default naming
    networks:
      ci_network:
        ipv4_address: 192.168.100.40

  webapp_postgres:
    # Remove custom container name to use default naming
    networks:
      ci_network:
        ipv4_address: 192.168.100.30

  postgres:
    # Remove custom container name to use default naming
    networks:
      ci_network:
        ipv4_address: 192.168.100.60

  minio:
    # Remove custom container name to use default naming
    networks:
      ci_network:
        ipv4_address: 192.168.100.50

# Custom network with fixed subnet for reliable IPs
networks:
  ci_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
