version: '3.8'

# GitHub CI specific Docker Compose overrides
services:
  opensearch-node1:
    hostname: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - path.repo=/mnt/snapshots
      - plugins.security.disabled=true
      - network.host=0.0.0.0
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./snapshots:/mnt/snapshots
    networks:
      opensearch-net:
        aliases:
          - opensearch-node1
          - opensearch1
    # Removed extra_hosts to avoid CI networking issues

  opensearch-node2:
    hostname: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - path.repo=/mnt/snapshots
      - plugins.security.disabled=true
      - network.host=0.0.0.0
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ./snapshots:/mnt/snapshots
    networks:
      opensearch-net:
        aliases:
          - opensearch-node2
          - opensearch2
    # Removed extra_hosts to avoid CI networking issues

  webapp:
    # Use multiple networks for proper service communication
    networks:
      - default
      - keycloak_network
      - opensearch-net
      - minio_network
    # Removed extra_hosts to avoid CI networking issues
    # Override environment to use more reliable networking
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - CONFIG_SOURCE=ENVIRONMENT_VARIABLES
      - DB_HOST=webapp_postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_SSL_ROOT_CERTIFICATE=/app/local_services/webapp_postgres_certs/root-ca.pem
      - SQLALCHEMY_SSL_MODE=disable
      - KEYCLOAK_BASE_URI=http://keycloak:8080
      - KEYCLOAK_CLIENT_ID=ayr-beta
      - KEYCLOAK_REALM_NAME=tdr
      - KEYCLOAK_CLIENT_SECRET=test-client-secret
      - AWS_ENDPOINT_URL=https://127.0.0.1:9000
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_REGION=eu-west-2
      - AWS_CA_BUNDLE=/app/local_services/minio_certs/root-ca.crt
      - SECRET_KEY=test-secret-key
      - DEFAULT_PAGE_SIZE=10
      - DEFAULT_DATE_FORMAT=DD/MM/YYYY
      - RECORD_BUCKET_NAME=test-record-download
      - FLASKS3_ACTIVE=False
      - FLASKS3_CDN_DOMAIN=localhost
      - FLASKS3_BUCKET_NAME=test-record-download
      - PERF_TEST=False
      # Use single OpenSearch endpoint with HTTP for CI
      - OPEN_SEARCH_HOST=http://opensearch-node1:9200
      - OPEN_SEARCH_USERNAME=admin
      - OPEN_SEARCH_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - OPEN_SEARCH_TIMEOUT=30
    # Remove links as they're redundant with extra_hosts
    links: []

  keycloak:
    hostname: keycloak
    networks:
      keycloak_network:
        aliases:
          - keycloak

  webapp_postgres:
    hostname: webapp_postgres
    networks:
      default:
        aliases:
          - webapp_postgres

  postgres:
    hostname: postgres
    networks:
      keycloak_network:
        aliases:
          - postgres

  minio:
    hostname: minio
    networks:
      minio_network:
        aliases:
          - minio

# Simplified networking for CI
networks:
  opensearch-net:
    driver: bridge
  keycloak_network:
    driver: bridge
  minio_network:
    driver: bridge
  default:
    driver: bridge