---
services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - plugins.security.ssl.transport.pemcert_filepath=/usr/share/opensearch/config/opensearch-node1.crt
      - plugins.security.ssl.transport.pemkey_filepath=/usr/share/opensearch/config/opensearch-node1.key
      - plugins.security.ssl.transport.pemtrustedcas_filepath=/usr/share/opensearch/config/root-ca.pem
      - plugins.security.ssl.http.enabled=true
      - plugins.security.ssl.http.pemcert_filepath=/usr/share/opensearch/config/opensearch-node1.crt
      - plugins.security.ssl.http.pemkey_filepath=/usr/share/opensearch/config/opensearch-node1.key
      - plugins.security.ssl.http.pemtrustedcas_filepath=/usr/share/opensearch/config/root-ca.pem
      - plugins.security.allow_unsafe_democertificates=true
      - plugins.security.allow_default_init_securityindex=true
      - path.repo=/mnt/snapshots
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./snapshots:/mnt/snapshots
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
    user: "0:0"
    command: [
      "bash", "-c",
      "yum install -y openssl util-linux && cd /usr/share/opensearch/config && openssl req -x509 -newkey rsa:2048 -nodes -keyout opensearch-node1.key -out opensearch-node1.crt -days 1 -subj '/CN=opensearch-node1' && openssl req -x509 -newkey rsa:2048 -nodes -keyout root-ca.key -out root-ca.pem -days 1 -subj '/CN=root-ca' && chown opensearch:opensearch opensearch-node1.* root-ca.* && chmod 644 opensearch-node1.key opensearch-node1.crt root-ca.key root-ca.pem && exec runuser -u opensearch -- /usr/share/opensearch/opensearch-docker-entrypoint.sh"
    ]

  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - plugins.security.ssl.transport.pemcert_filepath=/usr/share/opensearch/config/opensearch-node2.crt
      - plugins.security.ssl.transport.pemkey_filepath=/usr/share/opensearch/config/opensearch-node2.key
      - plugins.security.ssl.transport.pemtrustedcas_filepath=/usr/share/opensearch/config/root-ca.pem
      - plugins.security.ssl.http.enabled=true
      - plugins.security.ssl.http.pemcert_filepath=/usr/share/opensearch/config/opensearch-node2.crt
      - plugins.security.ssl.http.pemkey_filepath=/usr/share/opensearch/config/opensearch-node2.key
      - plugins.security.ssl.http.pemtrustedcas_filepath=/usr/share/opensearch/config/root-ca.pem
      - plugins.security.allow_unsafe_democertificates=true
      - plugins.security.allow_default_init_securityindex=true
      - path.repo=/mnt/snapshots
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ./snapshots:/mnt/snapshots
    networks:
      - opensearch-net
    user: "0:0"
    command: [
      "bash", "-c",
      "yum install -y openssl util-linux && cd /usr/share/opensearch/config && openssl req -x509 -newkey rsa:2048 -nodes -keyout opensearch-node2.key -out opensearch-node2.crt -days 1 -subj '/CN=opensearch-node2' && openssl req -x509 -newkey rsa:2048 -nodes -keyout root-ca.key -out root-ca.pem -days 1 -subj '/CN=root-ca' && chown opensearch:opensearch opensearch-node2.* root-ca.* && chmod 644 opensearch-node2.key opensearch-node2.crt root-ca.key root-ca.pem && exec runuser -u opensearch -- /usr/share/opensearch/opensearch-docker-entrypoint.sh"
    ]
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - '5601'
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - opensearch-net
  postgres:
    image: postgres:17.6
    volumes:
      - kc_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${KC_POSTGRES_PORT}:5432
    networks:
      - keycloak_network

  webapp_postgres:
    image: postgres:17.6
    volumes:
      - webapp_postgres_data:/var/lib/postgresql/data
      - ./dev-data.sql:/docker-entrypoint-initdb.d/dev-data.sql
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - ${WEBAPP_POSTGRES_PORT}:5432
    networks:
      - default

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    command: start-dev --import-realm
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_SSL_REQUIRED: none
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./import:/opt/keycloak/data/import
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ~/minio/data:/data
      - ./minio_certs/root-ca.crt:/root/.minio/certs/CAs/my-ca.crt
      - ./minio_certs/minio.key:/root/.minio/certs/private.key
      - ./minio_certs/minio.crt:/root/.minio/certs/public.crt
    command: server /data --console-address ":9001"

  webapp:
    env_file:
      - .docker.env
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - CONFIG_SOURCE=ENVIRONMENT_VARIABLES
      - DB_HOST=webapp_postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_SSL_ROOT_CERTIFICATE=/app/local_services/webapp_postgres_certs/root-ca.pem
      - SQLALCHEMY_SSL_MODE=disable
      - KEYCLOAK_BASE_URI=http://keycloak:8080
      - KEYCLOAK_CLIENT_ID=ayr-beta
      - KEYCLOAK_REALM_NAME=tdr
      - KEYCLOAK_CLIENT_SECRET=test-client-secret
      - AWS_ENDPOINT_URL=https://127.0.0.1:9000
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_REGION=eu-west-2
      - SECRET_KEY=test-secret-key
      - DEFAULT_PAGE_SIZE=10
      - DEFAULT_DATE_FORMAT=DD/MM/YYYY
      - RECORD_BUCKET_NAME=test-record-download
      - FLASKS3_ACTIVE=False
      - FLASKS3_CDN_DOMAIN=localhost
      - FLASKS3_BUCKET_NAME=test-record-download
      - PERF_TEST=False
      - OPEN_SEARCH_HOST=https://opensearch-node1:9200
      - OPEN_SEARCH_USERNAME=admin
      - OPEN_SEARCH_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - OPEN_SEARCH_CA_CERTS=/app/local_services/opensearch_certs/root-ca.pem
      - OPEN_SEARCH_TIMEOUT=10
    depends_on:
      - webapp_postgres
      - keycloak
      - minio
      - opensearch-node1
    networks:
      - default
      - keycloak_network
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:
  kc_postgres_data:
    driver: local
  webapp_postgres_data:
    driver: local

networks:
  default:
    driver: bridge
  opensearch-net:
  keycloak_network:
    driver: bridge
