version: '3.8'

# GitHub CI specific Docker Compose overrides - Simplified single network approach
services:
  # Single OpenSearch node for CI simplicity
  opensearch-node1:
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - plugins.security.disabled=true
      - network.host=0.0.0.0
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    networks:
      - default

  # Disable node2 for CI to simplify
  opensearch-node2:
    deploy:
      replicas: 0

  webapp:
    # Simplified networking - use default network only
    networks:
      - default
    # Connect to OpenSearch via localhost
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - CONFIG_SOURCE=ENVIRONMENT_VARIABLES
      - DB_HOST=webapp_postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_SSL_ROOT_CERTIFICATE=/app/local_services/webapp_postgres_certs/root-ca.pem
      - SQLALCHEMY_SSL_MODE=disable
      - KEYCLOAK_BASE_URI=http://keycloak:8080
      - KEYCLOAK_CLIENT_ID=ayr-beta
      - KEYCLOAK_REALM_NAME=tdr
      - KEYCLOAK_CLIENT_SECRET=test-client-secret
      - AWS_ENDPOINT_URL=https://127.0.0.1:9000
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_REGION=eu-west-2
      - AWS_CA_BUNDLE=/app/local_services/minio_certs/root-ca.crt
      - SECRET_KEY=test-secret-key
      - DEFAULT_PAGE_SIZE=10
      - DEFAULT_DATE_FORMAT=DD/MM/YYYY
      - RECORD_BUCKET_NAME=test-record-download
      - FLASKS3_ACTIVE=False
      - FLASKS3_CDN_DOMAIN=localhost
      - FLASKS3_BUCKET_NAME=test-record-download
      - PERF_TEST=False
      # Use service name for OpenSearch in CI (single network)
      - OPEN_SEARCH_HOST=http://opensearch-node1:9200
      - OPEN_SEARCH_USERNAME=admin
      - OPEN_SEARCH_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - OPEN_SEARCH_TIMEOUT=30
    depends_on:
      - webapp_postgres
      - keycloak
      - minio
      - opensearch-node1

  # Put all services on default network for CI simplicity
  
  keycloak:
    networks:
      - default

  webapp_postgres:
    networks:
      - default

  postgres:
    networks:
      - default

  minio:
    networks:
      - default

# Use only default network for CI simplicity
networks:
  default:
    driver: bridge