services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=false
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
      - path.repo=/mnt/snapshots
      - cluster.name=opensearch-ci
      - node.name=opensearch-ci-node1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./snapshots:/mnt/snapshots
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]'
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node1

  opensearch-restore:
    image: python
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    depends_on:
      - opensearch-node1
    networks:
      - opensearch-net
    command: |
      bash -c "
        # Register the snapshot repository (no auth needed)
        curl -s -X PUT 'http://opensearch-node1:9200/_snapshot/my-fs-repository' -H 'Content-Type: application/json' -d '{\"type\": \"fs\", \"settings\": {\"location\": \"/mnt/snapshots\"}}'

        echo 'Repository registered.'

        # Delete existing documents index if it exists
        curl -s -X DELETE 'http://opensearch-node1:9200/documents' || echo 'No existing index to delete'

        echo 'Existing index cleared.'

        # Restore from snapshot (no auth needed)
        curl -s -X POST 'http://opensearch-node1:9200/_snapshot/my-fs-repository/1/_restore' -H 'Content-Type: application/json' -d '{\"indices\": \"documents\", \"include_global_state\": false}'

        echo 'Restore completed.'

        # Keep container running briefly to see results
        sleep 10
      "

  postgres:
    image: postgres:18.0
    volumes:
      - kc_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${KC_POSTGRES_PORT}:5432
    networks:
      - keycloak_network

  webapp_postgres:
    image: postgres:18.0
    user: postgres
    volumes:
      - webapp_postgres_data:/var/lib/postgresql/data
      - ./dev-data.sql:/docker-entrypoint-initdb.d/dev-data.sql
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - ${WEBAPP_POSTGRES_PORT}:5432
    networks:
      - default
    command: ["postgres"]

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.1
    command: start-dev --import-realm --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_SSL_REQUIRED: none
      KC_PROXY: edge
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./import:/opt/keycloak/data/import
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master/.well-known/openid-configuration"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 30
    #   start_period: 10s

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      minio_network:
        aliases:
          - 127.0.0.1

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - ./files:/tmp/files:ro
    networks:
      - minio_network
    entrypoint: >
      /bin/sh -c "
      sleep 15;
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/test-record-download --ignore-existing;
      /usr/bin/mc cp --recursive /tmp/files/ myminio/test-record-download/ || echo 'No files to copy or copy failed';
      "

  socat-localhost:
    image: alpine/socat
    command: tcp-listen:9000,fork,reuseaddr tcp-connect:minio:9000
    network_mode: service:webapp
    depends_on:
      - minio

  webapp:
    env_file:
      - .docker.env
    image: da-ayr-beta-webapp-webapp:latest
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: webapp
    command: >
      sh -c "
        if [ ! -f /app/cert.pem ]; then
          echo 'Generating SSL certificates for webapp...'
          openssl req -x509 -newkey rsa:2048 -nodes -out /app/cert.pem -keyout /app/key.pem -days 365 -subj '/C=GB/ST=Test/L=Test/O=Test/CN=localhost'
        fi &&
        poetry run flask run --host=0.0.0.0 --port=5000 --debug
      "
    ports:
      - "5000:5000"
    volumes:
      # Mount source code for hot reloading
      - ..:/app
      # Exclude build artifacts and cache directories
      - /app/node_modules
      - /app/.git
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/.venv
      # Mount certificates
      - ./minio_certs:/app/local_services/minio_certs
      - ./opensearch_certs:/app/local_services/opensearch_certs
      - ./webapp_postgres_certs:/app/local_services/webapp_postgres_certs
    networks:
      - default
      - keycloak_network
      - opensearch-net
      - minio_network
    links:
      - opensearch-node1
    depends_on:
      - webapp_postgres
      - keycloak
      - minio
      - opensearch-node1
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

volumes:
  opensearch-data1:
  opensearch-data2:
  kc_postgres_data:
    driver: local
  webapp_postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  default:
    driver: bridge
  opensearch-net:
  keycloak_network:
    driver: bridge
  minio_network:
    driver: bridge
