name: Run E2E Tests

on:
  pull_request:
  merge_group:

jobs:
  e2e_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: 3.11

    - name: Install Poetry
      run: pip install poetry

    - name: Set up environment variables
      run: | # pragma: allowlist secret
        cd local_services
        cat > .docker.env << EOF
        OPENSEARCH_INITIAL_ADMIN_PASSWORD=FOOBARCARabc123!
        POSTGRES_USER=local_db_user
        POSTGRES_PASSWORD=local_db_user_password
        POSTGRES_DB=local_db
        KC_POSTGRES_PORT=5432
        WEBAPP_POSTGRES_PORT=5433
        KEYCLOAK_ADMIN=admin
        KEYCLOAK_ADMIN_PASSWORD=password
        MINIO_ROOT_USER=ROOTNAME
        MINIO_ROOT_PASSWORD=CHANGEME123
        EOF

    - name: Start services
      run: |
        cd local_services
        export CONFIG_SOURCE=ENVIRONMENT_VARIABLES
        export OPENSEARCH_INITIAL_ADMIN_PASSWORD=FOOBARCARabc123!
        export POSTGRES_USER=local_db_user
        export POSTGRES_PASSWORD=local_db_user_password
        export POSTGRES_DB=local_db
        export KC_POSTGRES_PORT=5432
        export WEBAPP_POSTGRES_PORT=5433
        export KEYCLOAK_ADMIN=admin
        export KEYCLOAK_ADMIN_PASSWORD=password
        export MINIO_ROOT_USER=ROOTNAME
        export MINIO_ROOT_PASSWORD=CHANGEME123
        docker compose -f docker-compose.yml up -d

    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to start"
        sleep 30

        # Check Docker services status
        cd local_services
        docker compose ps

        # Check webapp logs
        echo "Webapp logs:"
        docker logs webapp --tail 20

        timeout 120 bash -c 'until curl -k -f https://127.0.0.1:8000 || curl -f http://127.0.0.1:8000; do sleep 2; done'

        # Wait for keycloak realm to be ready
        timeout 120 bash -c 'until curl -f http://127.0.0.1:8080/realms/tdr/.well-known/openid-configuration; do sleep 2; done'



    - name: Install E2E test dependencies
      run: |
        cd e2e_tests
        poetry install --no-root
        poetry run playwright install --with-deps chromium

    - name: Run E2E tests
      run: |
        cd e2e_tests
        poetry run python -m pytest . -v --browser=chromium
      env:
        WEBAPP_URL: https://127.0.0.1:8000
        KEYCLOAK_BASE_URI: http://127.0.0.1:8080
        KEYCLOAK_REALM_NAME: tdr
        KEYCLOAK_CLIENT_ID: ayr-beta
        KEYCLOAK_CLIENT_SECRET: test-client-secret # pragma: allowlist secret

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: e2e_tests/playwright-report/
        retention-days: 7

    - name: Upload screenshots on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-screenshots
        path: e2e_tests/test-results/
        retention-days: 7

    - name: Stop services
      if: always()
      run: |
        cd local_services
        docker compose -f docker-compose.yml down -v
        docker system prune -f
