name: Pre-commit check
on:
  pull_request:
  merge_group:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
