name: Trigger Non Prod Deployment CD

on:
    push:
      branches:
        - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [int, test-one]


    steps:
      - name: Trigger Application Deployment in da-ayr-terraform private repo
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/nationalarchives/da-ayr-terraform/actions/workflows/deploy_application_code.yml/dispatches \
          -d '{"ref":"main","inputs":{"environment": "${{ matrix.environment }}"}}'
