name: Run Unit Tests

on:
  pull_request:
  merge_group:

jobs:
  app_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: 3.11

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Install Node dependencies
      run: npm install

    - name: Run build script
      run: ./build.sh

    - name: Build CSS
      run: npm run build

    - name: Run App unit tests
      run: AWS_DEFAULT_REGION=eu-west-2 poetry run pytest --cov=app/main --cov-report term-missing -rsa -vvv app/tests

    - name: Generate coverage XML
      run: poetry run coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24

  data_management_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Run Docker Compose Tests
      run: docker compose -f docker-compose.test.yml up --exit-code-from opensearch_indexer_tests

    - name: Copy coverage file from shared volume
      run: |
        cp ./test_results/coverage.xml ./coverage.xml || echo "Coverage file not found"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24
      with:
        file: ./coverage.xml

  e2e_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client jq

    - name: Generate SSL certificates for local services
      run: |
        # Generate PostgreSQL certificates
        cd local_services/webapp_postgres_certs
        ./generate_webapp_postgres_certs.sh
        
        # Generate OpenSearch certificates  
        cd ../opensearch_certs
        ./generate_opensearch_certs.sh
        
        # Fix permissions for PostgreSQL SSL certificates
        cd ../webapp_postgres_certs
        chmod 600 postgres_localhost.key
        chmod 644 postgres_localhost.crt
        chmod 644 root-ca.pem

    - name: Create local services environment file
      run: |
        cp local_services/.env.template local_services/.env

    - name: Create CI-specific docker-compose override
      run: |
        cat > local_services/docker-compose.override.yml << 'EOF'
        services:
          webapp_postgres:
            volumes:
              - webapp_postgres_data:/var/lib/postgresql/data
              - ./dev-data.sql:/docker-entrypoint-initdb.d/dev-data.sql
            command: ["postgres"]
          
          opensearch-node1:
            environment:
              - cluster.name=opensearch-cluster
              - node.name=opensearch-node1
              - discovery.type=single-node
              - bootstrap.memory_lock=true
              - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
              - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
              - DISABLE_SECURITY_PLUGIN=true
            volumes:
              - opensearch-data1:/usr/share/opensearch/data
            ports:
              - 9200:9200
              - 9600:9600
            networks:
              - opensearch-net
        
          opensearch-node2:
            deploy:
              replicas: 0
        EOF

    - name: Start local services
      run: |
        cd local_services && docker compose up -d

    - name: Wait for services to be ready
      run: |
        echo "Checking Docker containers status..."
        docker ps
        
        echo "Checking webapp_postgres container logs..."
        sleep 10  # Give containers a moment to start
        docker logs local_services-webapp_postgres-1 --tail 20
        
        echo "Waiting for PostgreSQL (webapp)..."
        timeout 300 bash -c 'until pg_isready -h localhost -p 5433 -U local_db_user; do echo "PostgreSQL not ready yet... ($(date))"; docker logs local_services-webapp_postgres-1 --tail 5; sleep 10; done'
        echo "PostgreSQL is ready"
        
        echo "Waiting for Keycloak..."
        echo "Checking if Keycloak container is running..."
        docker logs local_services-keycloak-1 --tail 10
        timeout 300 bash -c 'until curl -f http://localhost:8080/realms/master 2>/dev/null; do echo "Keycloak not ready yet... ($(date))"; sleep 10; done'
        echo "Keycloak is ready"
        
        echo "Configuring Keycloak client secret..."
        sleep 10  # Give Keycloak time to fully initialize
        
        # Get admin access token
        ADMIN_TOKEN=$(curl -s -X POST "http://localhost:8080/realms/master/protocol/openid-connect/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "username=admin" \
          -d "password=password" \
          -d "grant_type=password" \
          -d "client_id=admin-cli" | jq -r '.access_token')
        
        # Check if tdr realm exists, if not wait for import
        until curl -s -H "Authorization: Bearer $ADMIN_TOKEN" "http://localhost:8080/admin/realms/tdr" | grep -q "tdr"; do
          echo "Waiting for tdr realm to be imported..."
          sleep 5
        done
        
        # Get client ID
        CLIENT_ID=$(curl -s -H "Authorization: Bearer $ADMIN_TOKEN" "http://localhost:8080/admin/realms/tdr/clients?clientId=ayr-beta" | jq -r '.[0].id')
        
        # Update client secret and enable service accounts
        curl -s -X PUT "http://localhost:8080/admin/realms/tdr/clients/$CLIENT_ID" \
          -H "Authorization: Bearer $ADMIN_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"secret":"test-client-secret","serviceAccountsEnabled":true,"directAccessGrantsEnabled":true}'
        
        # Get realm management client ID 
        REALM_MGMT_CLIENT_ID=$(curl -s -H "Authorization: Bearer $ADMIN_TOKEN" "http://localhost:8080/admin/realms/tdr/clients?clientId=realm-management" | jq -r '.[0].id')
        
        # Get manage-users role ID
        MANAGE_USERS_ROLE_ID=$(curl -s -H "Authorization: Bearer $ADMIN_TOKEN" "http://localhost:8080/admin/realms/tdr/clients/$REALM_MGMT_CLIENT_ID/roles/manage-users" | jq -r '.id')
        
        # Get service account user ID for ayr-beta client
        SERVICE_ACCOUNT_USER_ID=$(curl -s -H "Authorization: Bearer $ADMIN_TOKEN" "http://localhost:8080/admin/realms/tdr/clients/$CLIENT_ID/service-account-user" | jq -r '.id')
        
        # Assign manage-users role to service account
        curl -s -X POST "http://localhost:8080/admin/realms/tdr/users/$SERVICE_ACCOUNT_USER_ID/role-mappings/clients/$REALM_MGMT_CLIENT_ID" \
          -H "Authorization: Bearer $ADMIN_TOKEN" \
          -H "Content-Type: application/json" \
          -d '[{"id":"'"$MANAGE_USERS_ROLE_ID"'","name":"manage-users"}]'
        
        echo "Keycloak client configured with admin permissions"
        
        echo "Creating missing groups..."
        
        # Create transferring_body_user parent group if it doesn't exist
        curl -s -X POST "http://localhost:8080/admin/realms/tdr/groups" \
          -H "Authorization: Bearer $ADMIN_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"name":"transferring_body_user","path":"/transferring_body_user"}' 2>/dev/null || true
        
        # Get transferring_body_user group ID
        TB_GROUP_ID=$(curl -s -H "Authorization: Bearer $ADMIN_TOKEN" "http://localhost:8080/admin/realms/tdr/groups?search=transferring_body_user" | jq -r '.[0].id')
        
        # Create "Testing A" subgroup under transferring_body_user
        if [ "$TB_GROUP_ID" != "null" ] && [ -n "$TB_GROUP_ID" ]; then
          curl -s -X POST "http://localhost:8080/admin/realms/tdr/groups/$TB_GROUP_ID/children" \
            -H "Authorization: Bearer $ADMIN_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"name":"Testing A","path":"/transferring_body_user/Testing A"}' 2>/dev/null || true
        fi
        
        echo "Missing groups created"
        
        echo "Creating test users..."
        
        # Create AAU test user
        AAU_USER_ID=$(curl -s -X POST "http://localhost:8080/admin/realms/tdr/users" \
          -H "Authorization: Bearer $ADMIN_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "username":"test-aau-user@example.com",
            "email":"test-aau-user@example.com",
            "firstName":"Test",
            "lastName":"AAU",
            "enabled":true,
            "credentials":[{"type":"password","value":"test-password","temporary":false}]
          }' | jq -r '.id' 2>/dev/null || echo "failed")
        
        # Create Standard test user  
        STANDARD_USER_ID=$(curl -s -X POST "http://localhost:8080/admin/realms/tdr/users" \
          -H "Authorization: Bearer $ADMIN_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "username":"test-standard-user@example.com",
            "email":"test-standard-user@example.com", 
            "firstName":"Test",
            "lastName":"Standard",
            "enabled":true,
            "credentials":[{"type":"password","value":"test-password","temporary":false}]
          }' | jq -r '.id' 2>/dev/null || echo "failed")
        
        # Get view_all group ID
        VIEW_ALL_GROUP_ID=$(curl -s -H "Authorization: Bearer $ADMIN_TOKEN" "http://localhost:8080/admin/realms/tdr/groups?search=view_all" | jq -r '.[0].id')
        
        # Add AAU user to view_all group
        curl -s -X PUT "http://localhost:8080/admin/realms/tdr/users/$AAU_USER_ID/groups/$VIEW_ALL_GROUP_ID" \
          -H "Authorization: Bearer $ADMIN_TOKEN"
        
        # Add Standard user to view_all group  
        curl -s -X PUT "http://localhost:8080/admin/realms/tdr/users/$STANDARD_USER_ID/groups/$VIEW_ALL_GROUP_ID" \
          -H "Authorization: Bearer $ADMIN_TOKEN"
        
        echo "Test users created and added to view_all group: AAU=$AAU_USER_ID, Standard=$STANDARD_USER_ID"
        
        echo "Skipping OpenSearch for CI - not essential for basic E2E tests"
        
        echo "Essential services (PostgreSQL, Keycloak, MinIO) are ready"

    - name: Skip OpenSearch data setup
      run: |
        echo "Skipping OpenSearch data setup for CI environment"

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: 3.11

    - name: Install Poetry
      run: pip install poetry

    - name: Install E2E test dependencies
      run: cd e2e_tests/ && poetry install --no-root && poetry run playwright install --with-deps

    - name: Set up webapp environment
      run: |
        cat > .env << 'EOF'
        CONFIG_SOURCE=ENVIRONMENT_VARIABLES
        KEYCLOAK_BASE_URI=http://localhost:8080
        KEYCLOAK_CLIENT_ID=ayr-beta
        KEYCLOAK_REALM_NAME=tdr
        KEYCLOAK_CLIENT_SECRET=test-client-secret
        DB_PORT=5433
        DB_HOST=localhost
        DB_NAME=local_db
        DB_USER=local_db_user
        DB_PASSWORD=local_db_user_password
        AWS_ENDPOINT_URL=http://localhost:9000
        AWS_ACCESS_KEY_ID=ROOTNAME
        AWS_SECRET_ACCESS_KEY=CHANGEME123
        SECRET_KEY=test-secret-key
        EOF

    - name: Run E2E tests
      env:
        KEYCLOAK_BASE_URI: http://localhost:8080
        KEYCLOAK_REALM_NAME: tdr
        KEYCLOAK_CLIENT_ID: ayr-beta
        KEYCLOAK_CLIENT_SECRET: test-client-secret
        AYR_AAU_USER_USERNAME: test-aau-user@example.com
        AYR_AAU_USER_PASSWORD: test-password
        AYR_STANDARD_USER_USERNAME: test-standard-user@example.com
        AYR_STANDARD_USER_PASSWORD: test-password
      run: |
        cd e2e_tests/ && poetry run pytest . --base-url=https://localhost:5000 -k "not test_css_no_visual_regression" -vvvv -rsa --slowmo 100 -ra -vvvv --tracing on --browser chromium

    - name: Show container logs on failure
      if: failure()
      run: |
        echo "=== Docker container status ==="
        docker ps -a
        echo "=== PostgreSQL logs ==="
        docker logs local_services-webapp_postgres-1 || echo "No webapp_postgres container found"
        echo "=== Keycloak logs ==="
        docker logs local_services-keycloak-1 || echo "No keycloak container found"
        echo "=== OpenSearch node1 logs ==="
        docker logs opensearch-node1 || echo "No opensearch-node1 container found"

    - name: Stop local services
      if: always()
      run: |
        cd local_services && docker compose down
